# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-14 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import doc.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to=doc.models.upload_location)),
                ('nrDoc', models.IntegerField()),
                ('dataDoc', models.DateField()),
                ('emitent', models.CharField(max_length=100)),
                ('beneficiar', models.CharField(max_length=100)),
                ('drumulNational', models.CharField(max_length=10)),
                ('pozitiaKilometrica', models.CharField(max_length=50)),
                ('partea', models.CharField(choices=[('d', 'Dreapta'), ('s', 'Stanga')], max_length=1)),
                ('drdp', models.CharField(max_length=20)),
                ('creat', models.DateTimeField(auto_now_add=True)),
                ('modificat', models.DateTimeField(auto_now=True)),
                ('rezolvat', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-creat', '-modificat'],
            },
        ),
    ]
