# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-14 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='drdp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
