# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-15 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0002_auto_20180314_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='drdp',
            field=models.CharField(blank=True, choices=[('Bucuresti', 'Bucuresti'), ('Craiova', 'Craiova'), ('Timisoara', 'Timisoara'), ('Cluj', 'Cluj'), ('Brasov', 'Brasov'), ('Iasi', 'Iasi'), ('Constanta', 'Constanta')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doc',
            name='partea',
            field=models.CharField(choices=[('Dreapta', 'Dreapta'), ('Stanga', 'Stanga')], max_length=1),
        ),
    ]
