# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-15 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0003_auto_20180315_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='partea',
            field=models.CharField(blank=True, choices=[('Dreapta', 'Dreapta'), ('Stanga', 'Stanga')], max_length=7, null=True),
        ),
    ]
