# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-15 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0004_auto_20180315_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='drdp',
            field=models.CharField(blank=True, choices=[('Bucuresti', 'Bucuresti'), ('Craiova', 'Craiova'), ('Timisoara', 'Timisoara'), ('Cluj', 'Cluj'), ('Brasov', 'Brasov'), ('Iasi', 'Iasi'), ('Constanta', 'Constanta')], max_length=10, null=True),
        ),
    ]
